name: Publish playlists

on:
  schedule:
    - cron:  '30 1 * * *'
  watch:
    types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Generate Playlists
      run: |
        npm run generate https://iptv-org.github.io/iptv/languages/cmn.m3u cmn.txt
        npm run generate https://iptv-org.github.io/iptv/languages/zho.m3u zho.txt
        npm run generate https://iptv-org.github.io/iptv/languages/xxx.m3u xxx.txt
        npm run generate https://iptv-org.github.io/iptv/languages/other.m3u other.txt
        npm run generate https://iptv-org.github.io/iptv/languages/yue.m3u yue.txt
        npm run generate https://iptv-org.github.io/iptv/languages/tw.m3u tw.txt
        cat cmn.txt zho.txt xxx.txt other.txt yue.txt tw.txt > tmp.txt

    - name: Clean
      run: rm -rf .github && ls -l .

    - name: Git init
      run: |
        git config --global user.name "Actions"
        git config --global user.email "actions@github.com"
 
    - name: Commit
      run: git add --all && git commit -m 'Deploy pages'

    - name: Push to GitHub Pages
      run: git checkout -b gh-pages && git push -f origin gh-pages
